stages:
  - test
  - pack
  - build

test:
  stage: test
  image: 115159323386.dkr.ecr.ap-southeast-2.amazonaws.com/base/scala-sbt:8-2-1-jdk-alpine
  cache:
    key: "$CI_JOB_STAGE"
    untracked: true
    paths:
      - "sbt-cache/ivy/cache"
      - "sbt-cache/boot"
      - "sbt-cache/sbtboot"
      - "sbt-cache/target"
  script:
    - sbt test
  except:
    - master
    - staging
    - develop
  tags:
    - qantas-loyalty


build:pack:
  stage: pack
  image: 115159323386.dkr.ecr.ap-southeast-2.amazonaws.com/base/scala-sbt:8-2-1-jdk-alpine
  cache:
    key: "$CI_COMMIT_REF_NAME"
    paths:
      - "sbt-cache/ivy/cache"
      - "sbt-cache/boot"
      - "sbt-cache/sbtboot"
      - "sbt-cache/target"
  script:
    - sbt test pack
  artifacts:
    paths:
      - target/pack
    expire_in: 20min
    when: always
  only:
    - master
    - staging
    - develop
  tags:
    - qantas-loyalty

build:docker:
  stage: build
  image: 115159323386.dkr.ecr.ap-southeast-2.amazonaws.com/base/docker:latest
  script:
    - apk add --no-cache make git wget bash groff less python py-pip
    - pip install awscli
    - export AWS_DEFAULT_REGION=ap-southeast-2
    - export AWS_REGION=ap-southeast-2
    - make
  only:
    - master
    - staging
    - develop
  tags:
    - qantas-loyalty
